//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_GameTracker_Emma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesTable
    {
        public int GameID { get; set; }
        public int Week { get; set; }
        public string Description { get; set; }
        public int TeamOneID { get; set; }
        public int TeamTwoID { get; set; }
        public int TeamOnePoints { get; set; }
        public int TeamTwoPoints { get; set; }
        public int Spectators { get; set; }
        public int Winner { get; set; }
    }
}
